### PR TITLE
Added a scope parameter to login with clinetID

### PR DESCRIPTION
**Pull request by ghost**
Adding the `scope` parameter gives apps the chance to ask for `read-only` permissions from the users providing more safety and giving apps a better chance of being authorised by YNAB users.

[YNAB docs about scope](https://api.youneedabudget.com/#oauth-authorization-parameters)

### CODE REVIEW

**Comment by ghost** [comment]
@dauby88 Would be lovely if you can take a look when you have a chance

**Review by dauby88 — CHANGES_REQUESTED** [review]
I like the addition of the permission scope. I would like to see it as a simple enum rather than a struct.

**Comment by ghost** [comment]
Changed to an enum.

**Comment by dauby88** [comment]
I like that a lot. Much cleaner!

**Review by dauby88 — APPROVED** [review]

**Pull request merged**
