### PR TITLE
Support default budget

### PR DESCRIPTION
**Pull request by ghost**
A couple of main things in the pull request

1. Supporting the "default budget", when you select in your API project in YNAB that users can select their default budget, you can pass "default" in the URL requests instead of the budget id to get info for that budget, I updated all the requests to support passing nil and then the functions will use "default" instead
2. I fixed the function to get the budget settings because the url was fetching the information of the budget without adding "/settings" at the end
https://api.youneedabudget.com/#oauth-default-budget

Also I updated the project settings to get rid of some Xcode nasty warnings about upgrading to Swift 5 & missing localisation files.

Indeed the last commit actually adds the BK prefix to all structs and classes to distinguish them and avoid any conflict with other libraries or app specific types.

### CODE REVIEW

**Comment by ghost** [comment]
@dauby88 Let me know what you think and if you merge it, do you think it would be possible to release a new version on cocoapods?

**Comment by dauby88** [comment]
Fixes for default budget and Swift 5 warnings look good!
However I don't want to prefix the classes/structs for this library. Swift gives automatic namespaces and it's no longer a common recommendation to prefix class names for libraries like it was working in ObjC.

**Comment by ghost** [comment]
Ok I will revert that one!

**Comment by ghost** [comment]
Should be done now

**Review by dauby88 — APPROVED** [review]
Looks good. I like the simplification that the `BaseController` brings.

**Pull request merged**
